name: Terraform Deploy

on:
  push:
    branches:
      - 'feature/*'
  pull_request:
    types:
      - closed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-west-2"

      - name: Terraform init
        run: |
          if [[ ${{ github.event_name }} == 'push' && (${{ github.event_path }} == *"root/modules"* 
            terraform init -detailed-exitcode
          else
            echo "No Terraform plan necessary for this directory."
          fi

      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan
        run: |
          if [[ ${{ github.event_name }} == 'push' && (${{ github.event_path }} == *"root/env/dev"* || ${{ github.event_path }} == *"root/env/test"* || ${{ github.event_path }} == *"root/env/prod"*) ]] && && steps.terraform_init.outputs.exitcode == '0'; then
            terraform plan -detailed-exitcode
          else
            echo "No Terraform plan necessary for this directory."
          fi

      - name: Terraform apply
        if: github.event.pull_request.merged == true && steps.terraform_plan.outputs.exitcode == '0'
        run: terraform apply --auto-approve
